[package]
name = "txn"
version = "0.2.0"
description = "C++ serialization framework inspired by serde"
authors = ["Geunryeol Park (misut)"]
license = "MIT"
type = "lib"
standard = 23

[dependencies.workspace]
refl = true
