[package]
name = "txn"
version = "0.4.0"
description = "C++ serialization framework inspired by serde"
authors = ["Geunryeol Park (misut)"]
license = "MIT"
type = "lib"
standard = 23

[dependencies]
"github.com/misut/cppx" = "0.1.0"
